name: Run tests
on: [push, pull_request]

jobs:
  # Note that if we want to keep testing on Python 3.6, we need to test on
  # an older ubuntu. Once we don't care about 3.6 any longer we can drop this.
  test-client-old-python:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ['3.6']
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Test
        run: |
          pip install -e .[test]
          py.test
  test-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8, 3.9, '3.10']
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Test
        run: |
          pip install -e .[test]
          py.test
